$color0 = rgb(464549)
$color1 = rgb(96CDFB)
$color2 = rgb(759DC3)
$color3 = rgb(607F9F)
$color4 = rgb(4C627D)
$color5 = rgb(37435A)
$color6 = rgb(1E1E2E)
$color7 = rgb(C2DEF5)
$color8 = rgb(889BAB)
$color9 = rgb(96CDFB)
$color10 = rgb(759DC3)
$color11 = rgb(607F9F)
$color12 = rgb(4C627D)
$color13 = rgb(37435A)
$color14 = rgb(1E1E2E)
$color15 = rgb(C2DEF5)
