general {
    lock_cmd = pidof hyprlock || hyprlock               # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session            # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on          # to avoid having to press a key twice to turn on the display.
}

listener {
    timeout = 480
    on-timeout = brightnessctl -s set 5% ; ddcutil --disable-dynamic-sleep setvcp 10 10
    on-resume = brightnessctl -r ; ddcutil --disable-dynamic-sleep setvcp 10 100
}

listener {
    timeout = 600                                       # 10min
    on-timeout = loginctl lock-session                  # lock screen when timeout has passed
}

listener {
    timeout = 660                                       # 11min
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' ; brightnessctl -r 
}

listener {
    timeout = 1800                                      # 30min
    on-timeout = $HOME/.config/hypr/scripts/suspend_if_unplugged.sh
}
