# Pavucontrol float oning
windowrule = float on, match:class (.*org.pulseaudio.pavucontrol.*)
windowrule = size 700 600,match:class (.*org.pulseaudio.pavucontrol.*)
windowrule = center on, match:class (.*org.pulseaudio.pavucontrol.*)
windowrule = pin on, match:class (.*org.pulseaudio.pavucontrol.*)

# Waypaper
windowrule = float on,match:class (.*waypaper.*)
windowrule = size 900 700,match:class (.*waypaper.*)
windowrule = center on,match:class (.*waypaper.*)
windowrule = pin on,match:class (.*waypaper.*)

# SwayNC
layerrule = blur on, match:namespace swaync-control-center
layerrule = blur on, match:namespace swaync-notification-window
layerrule = ignore_alpha 0, match:namespace swaync-control-center
layerrule = ignore_alpha 0, match:namespace swaync-notification-window
layerrule = ignore_alpha 0.5, match:namespace swaync-control-center
layerrule = ignore_alpha 0.5, match:namespace swaync-notification-window
windowrule {
    name = no_anim-swaync
    match:class = ^(swaync)$

    no_anim = on
}
layerrule = no_anim on, match:namespace swaync-control-center
layerrule = no_anim on, match:namespace swaync-notification-window


# Blueman Manager
windowrule = float on,match:class (blueman-manager)
windowrule = size 800 600,match:class (blueman-manager)
windowrule = center on,match:class (blueman-manager)

# nwg-look
windowrule = float on,match:class (nwg-look)
windowrule = size 700 600,match:class (nwg-look)
windowrule = move 10% 20%,match:class (nwg-look)
windowrule = pin on,match:class (nwg-look)

# nwg-displays
windowrule = float on,match:class (nwg-displays)
windowrule = size 900 600,match:class (nwg-displays)
windowrule = move 10% 20%,match:class (nwg-displays)
windowrule = pin on,match:class (nwg-displays)

# System Mission center on
windowrule = float on, match:class (io.missioncenter on.MissionCenter)
windowrule = pin on, match:class (io.missioncenter on.MissionCenter)
windowrule = center on, match:class (io.missioncenter.MissionCenter)
windowrule = size 900 600, match:class (io.missioncenter on.MissionCenter)

# System Mission center on Preference Window
windowrule = float on, match:class (missioncenter on), match:title ^(Preferences)$
windowrule = pin on, match:class (missioncenter on), match:title ^(Preferences)$
windowrule = center on, match:class (missioncenter), match:title ^(Preferences)$

# Gnome Calculator
windowrule = float on,match:class (org.gnome.Calculator)
windowrule = size 700 600,match:class (org.gnome.Calculator)
windowrule = center on,match:class (org.gnome.Calculator)

# Hyprland Share Picker
windowrule = float on, match:class (hyprland-share-picker)
windowrule = pin on, match:class (hyprland-share-picker)
windowrule = center on, match:title match:class (hyprland-share-picker)
windowrule = size 600 400,match:class (hyprland-share-picker)

# General float oning
windowrule = float on,match:class (dotfiles-floating)
windowrule = size 1000 700,match:class (dotfiles-float oning)
windowrule = center on,match:class (dotfiles-float oning)

# float on and center on file pickers
windowrule = float on, match:class xdg-desktop-portal-gtk, match:title ^(Open.*Files?|Save.*Files?|All Files|Save)
windowrule = center on, match:class xdg-desktop-portal-gtk, match:title ^(Open.*Files?|Save.*Files?|All Files|Save)

# XDG Desktop Portal
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# QT
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1

# GDK
env = GDK_SCALE,1

# Toolkit Backend
env = GDK_BACKEND,wayland,x11,*
env = CLUTTER_BACKEND,wayland

# Mozilla
env = MOZ_ENABLE_WAYLAND,1

# Set the cursor size for xcursor
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# Ozone
env = OZONE_PLATFORM,wayland
env = ELECTRON_OZONE_PLATFORM_HINT,wayland

# XWayland
xwayland {
  force_zero_scaling = true
}
